---
title: "Untitled"
output: html_document
date: "2023-11-28"
---

```{r setup , message = FALSE, warning = FALSE, include=F}
# global default settings for chunks
knitr::opts_chunk$set( eval = TRUE, warning = FALSE, message = FALSE, echo = T,
                      fig.dim = c(6, 3),
                      fig.width = 9,
                      fig.height = 5,
                      dpi = 300,
                      fig.pos = "!h"
  )

Packages <- c("tidyverse","arsenal","rentrez", "lubridate","polite","rvest")
invisible(lapply(Packages, library, character.only = TRUE))

theme_set(theme_minimal() +
    theme(legend.position = "bottom") +
    theme(plot.title = element_text(hjust = 0.5, size = 12),
    plot.subtitle = element_text(hjust = 0.5, size = 8))
  )

my_controls <- arsenal::tableby.control(
    test = T,
    total = T,
    numeric.test = "kwt", cat.test = "chisq",
    numeric.stats = c("N", "meansd", "medianq1q3", "range", "Nmiss2"),
    cat.stats = c("countpct", "Nmiss2"),
    stats.labels = list(
    meansd = "Mean (SD)",
    medianq1q3 = "Median (Q1, Q3)",
    range = "Min - Max",
    Nmiss2 = "Missing"
  )
)
my_controls_row <- arsenal::tableby.control(
    test = T, total = T,
    numeric.test = "kwt", cat.test = "chisq",
    numeric.stats = c("N", "meansd", "medianq1q3", "range", "Nmiss2")
    , cat.stats = c("countrowpct", "Nmiss2"),
    stats.labels = list(
    meansd = "Mean (SD)",
    medianq1q3 = "Median (Q1, Q3)",
    range = "Min - Max",
    Nmiss2 = "Missing"
  )
)
```


```{r}



get_pubmed(name1 = "Richa Deshpande",
           hiredate = "1/3/2023", 
           affiliation1 = "Mount Sinai") 

article_data(name1 = "Richa Deshpande",
           hiredate = "1/3/2023", 
           affiliation1 = "Mount Sinai",
          name2 = "",
          affiliation2 = "",
          affiliation3 = "") 

h_index(name1 = "Richa Deshpande",
           hiredate = "1/3/2023", 
           affiliation1 = "Mount Sinai") 

article_data(name1 = "Steven Lawrence",
             name2 = "Richa Dashpande",
           hiredate = "1/3/2023", 
           affiliation1 = "Mount Sinai",
        affiliation2 = "New York University",
        affiliation3 = "Medgar Evers") 
              
              

scholar::get_scholar_id(last_name = "Deshpande",
                        first_name =  "Richa",
                        affiliation =  "Mount Sinai")

```

```{r}
get_article_cite_history("Toward Safer Opioid Prescribing in HIV care (TOWER): a mixed-methods, cluster-randomized trial.")

title = "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=Toward+Safer+Opioid+Prescribing+in+HIV+care+%28TOWER%29%3A+a+mixed-methods%2C+cluster-randomized+trial.&btnG="

"https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=Phenotyping+autonomic+neuropathy+using+principal+component+analysis.&btnG="

title = "Phenotyping autonomic neuropathy using principal component analysis."
title = "Skin Bleaching Among African and Afro-Caribbean Women in New York City: Primary Findings from a P30 Pilot Study"
title = "Impact of New York State's Health Home program on access to care among patients with diabetes."
base_url <- 'https://scholar.google.com/scholar'
query <- paste0("?q=", URLencode(title))
page <- rvest::read_html(paste(base_url, query, sep = ""))
first_result <- rvest::html_nodes(page, '.gs_r')[1]
article_link <- rvest::html_node(first_result, 'a') %>% rvest::html_attr("href")


article_link="https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=Phenotyping+autonomic+neuropathy+using+principal+component+analysis.&btnG="

article_link = "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=Skin+bleaching+among+African+and+Afro-Caribbean+women+in+New+York+City%3A+Primary+findings+from+a+P30+pilot+study&btnG="

article_link = "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=Impact+of+New+York+State%27s+Health+Home+program+on+access+to+care+among+patients+with+diabetes.&btnG="

article_link = "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=Impact+of+New+York+State%27s+Health+Home+program+on+access+to+care+among+patients+with+diabetes.&btnG="

#https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=Impact+of+New+York+State%27s+Health+Home+program+on+access+to+care+among+patients+with+diabetes.&btnG=

article_link = get_article_url("Toward Safer Opioid Prescribing in HIV care (TOWER): a mixed-methods, cluster-randomized trial.")

# "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C33&q=Impact%20of%20New%20York%20State's%20Health%20Home%20program%20on%20access%20to%20care%20among%20patients%20with%20diabetes."

page <- rvest::read_html(article_link)
XML::htmlTreeParse(page) %>% XML::xmlNode('//*[@id="gs_res_ccl_mid"]/div[contains(@class, "gs_fl")]//a[contains(text(), "Cited by")]')

rvest::html_node(page, xpath = '/html/body/div/div[@id="gs_bdy"]/div[@id="gs_bdy_ccl"]')

rvest::html_node(page, xpath = '//*[@id="gs_res_ccl_mid"]/div[contains(@class, "gs_fl")]//a[contains(text(), "Cited by")]') %>% rvest::html_text()


rvest::html_node(page, xpath = '//*[@id="gs_res_ccl_mid"]')# %>% rvest::html_text()


rvest::html_node(page, xpath = '//*[@id="gs_res_ccl_mid"]/div/div[2]/div[5]/a[3]') %>% rvest::html_text()

node <- rvest::html_node(page, xpath = '//*[@id="gs_res_ccl_mid"]/div/div/div[3]/a[3]')
cited_by_count <- rvest::html_text(node) 

get_cited("Phenotyping autonomic neuropathy using principal component analysis.")


```



```{r}

session = polite::bow("", force = T)

session = polite::bow("https://www.cheese.com/by_type", force = T)

scrape(session, query=list(t="semi-soft", per_page=1)) %>%
  html_node('//*[@id="gs_res_ccl_mid"]/div[contains(@class, "gs_fl")]//a[contains(text(), "Cited by")]') %>% 
  html_text()

#\code{\link{get_scholar_resp}} fun



curl --get https://serpapi.com/search \
 -d engine="google_scholar_author" \
 -d view_op="view_citation" \
 -d citation_id="LSsXyncAAAAJ:9yKSN-GCB0IC" \
 -d api_key="secret_api_key"

article_link = get_article_url("Phenotyping autonomic neuropathy using principal component analysis.")

page = scholar::get_scholar_resp(attempts_left = 1,url =article_link )

page2 = rvest::read_html(page)
rvest::html_node(page2, xpath = '//*[@id="gs_res_ccl_mid"]/div/div[contains(@class, "gs_ri")]/div[contains(@class, "gs_fl")]//a[contains(text(), "Cited by")]')%>%
    rvest::html_text()
```

```{r}
#https://link.springer.com/article/10.1186/s12874-022-01608-7
query = query_func(name1 = "Steven Lawrence",
            affiliation1 = "Mount Sinai",
           affiliation2 = "New York University")

# queries author article ID's by name
  ids <- entrez_search("pubmed", query, retmax = 10000)$ids

  # pulls records by ID's
  rec<-  entrez_fetch("pubmed", ids[4], rettype = "xml")

  # parses meta information
  parsed <- XML::xmlTreeParse(rec, useInternalNodes = TRUE)

XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/MedlineCitation//AuthorList/Author')) %>% 
  data.frame() %>% 
  select(LastName, ForeName) 












## co author's name can change i.e: marriage occurs
## co author's can have the same name thus won't count as 2 separate names 
```


```{r}

query = query_func(name1 = "Emma Benn", affiliation1 = "Mount Sinai", name2 = "", affiliation2 = "", affiliation3 = "")

article_title = "Circadian Rhythm Disruption as a Contributor to Racial Disparities in Prostate Cancer."

article_link = get_article_url(article_title)

responce = scholar::get_scholar_resp(attempts_left = 1, url =article_link )
page = rvest::read_html(responce)
  cite_string = rvest::html_node(page, xpath = '//*[@id="gs_res_ccl_mid"]/div/div[contains(@class, "gs_ri")]/div[contains(@class, "gs_fl")]//a[contains(text(), "Cited by")]')%>%
  
    rvest::html_text()
  
  rvest::html_node(page, xpath = '/html/body/div/div[10]')
  
ids =  entrez_search("pubmed", paste0(query," ","AND"," ","('2023/01/01'[Date - Publication]:'2024/01/01'[Date - Publication])"), retmax = 10000)$ids
#37923971

recs = entrez_fetch("pubmed", ids, rettype = "xml")
parsed <- XML::xmlTreeParse(recs, useInternalNodes = TRUE)
XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/MedlineCitation/PMID'))

pub_citefunc(37923971)

```

```{r}

num_cores <- parallel::detectCores()  # This detects the number of available cores

# Set up a cluster using the detected number of cores
cl <- parallel::makeCluster(num_cores)
# Parallelize the function using the 'parLapply' function
result_parallel <- parallel::parLapply()cl = cl, article_data(recs, "01/01/2023"))

# Close the cluster after finishing computations
stopCluster(cl)

  citatations= parallel::parLapply(cl,ids,pub_citefunc) 
  
  citatations %>% tibble() %>% 
    unnest() %>% 
    rename("citations" = ".") %>% 
    mutate(citations= replace_na(citations,0))
```

```{r}
page = rvest::read_html( "https://pubmed.ncbi.nlm.nih.gov/36291899/")
#/html/body/div[5]/main/div[7]/ul
node = rvest::html_node(page, xpath = '/html/body/div[5]/main/div[6]/ul' )

node %>% as.character() %>% stringr::str_count(pattern = "<li")

#https://pubmed.ncbi.nlm.nih.gov/37307284/

rvest::html_node("https://pubmed.ncbi.nlm.nih.gov/?linkname=pubmed_pubmed_citedin&from_uid=37307284")

#https://pubmed.ncbi.nlm.nih.gov/?linkname=pubmed_pubmed_citedin&from_uid=

pub_citefunc <- function(id){
  

cite_link = paste0("https://pubmed.ncbi.nlm.nih.gov/?linkname=pubmed_pubmed_citedin&from_uid=",id)
session = polite::bow(cite_link, force = T)
 page = scrape(session, query=list(t="semi-soft", per_page=1)) 


(rvest::html_node(page, xpath = '/html/body/main/div[9]/div[2]/div[2]/div[1]/div[1]/h3/span') %>% rvest::html_text() %>% as.numeric())-1
}

tab = tibble(
  ids = ids[10:35]
) %>% 
  mutate(outcome = map(ids, pub_citefunc)) %>% 
  unnest(outcome)


cite_link = paste0("https://pubmed.ncbi.nlm.nih.gov/?linkname=pubmed_pubmed_citedin&from_uid=",37645610)
session = polite::bow(cite_link, force = T)
 page = scrape(session, query=list(t="semi-soft", per_page=1)) 
 
 rvest::html_node(page, xpath = '/html/body/main/div[9]/div[2]/div[2]/div[1]/div[1]/h3/span') %>% rvest::html_text() 
 
 ## Need to set up a multi threading function that will run the function using separate threads when there are more than 5 articles. 
 
```

```{r}



get_coauthor_count<- function(recs){

  parsed = XML::xmlTreeParse(recs, useInternalNodes = TRUE)

names = cbind(forename = XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/MedlineCitation//AuthorList/Author/ForeName')) ,
         Lastname = XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/MedlineCitation//AuthorList/Author/LastName')) )
  colnames(names) = c("forename","lastname")

n = names %>% 
  separate(forename, into = c("firstname","x"),sep = " ") %>%
  select( -x) %>%
  unique() %>%
  arrange(firstname) %>%
  summarize(n = n()-1) %>%
  pull(n)

list(names,n)

}

 hiredate = "01/01/2024"
    specific_date = lubridate::mdy(hiredate)
    two_years_prior_date <- specific_date %m-% years(2)
    
co_tab = get_coauthor_count(ids,two_years_prior_date,specific_date)



article_data(parsed)


```

```{r}
query = query_func("Emma Benn", "", affiliation1 = "Mount Sinai", affiliation2 = "Columbia University", affiliation3 = "")

ids =  entrez_search( "pubmed", query, retmax = 10000)$ids
recs = entrez_fetch("pubmed", ids, rettype = "xml")
parsed = XML::xmlTreeParse(recs, useInternalNodes = TRUE)

tab = article_data(parsed)

tab %>% 
 # unnest(citations) %>% 
  arrange(-citations) %>%
 mutate(order = dplyr::row_number(),
           ind = if_else(citations >= order, 1,0)) %>%
    dplyr::summarize(h_index = sum(ind, na.rm = T)) %>% 
    pull(h_index)
```


```{r}

names = cbind(forename = XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/MedlineCitation//AuthorList/Author/ForeName')) ,
                Lastname = XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/MedlineCitation//AuthorList/Author/LastName')),
                pubdates = XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/PubmedData/History/PubMedPubDate[@PubStatus="pubmed"]')))

tibble(forenames =  XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/MedlineCitation//AuthorList/Author/ForeName')),
       lastnames = XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/MedlineCitation//AuthorList/Author/LastName')),
       dates = XML::xmlToDataFrame(nodes = XML::getNodeSet(parsed, '//PubmedArticle/PubmedData/History/PubMedPubDate[@PubStatus="pubmed"]')) )

  colnames(names) = c("forename","lastname","dates")
  
  name_tab = names %>%
    tibble() %>%
    mutate(date = paste(pubdates.Month,pubdates.Day,pubdates.Year, sep = "/") %>% lubridate::mdy()
    ) %>%
    separate(forename, into = c("firstname","x"),sep = " ") %>%
    select( -x) %>%
    arrange(lastname) %>%
    unique()

  n = name_tab %>%
    summarize(n = n()-1) %>%
    pull(n)

  list(name_tab,n)
```

```{r}



cite_link = paste0("https://pubmed.ncbi.nlm.nih.gov/?linkname=pubmed_pubmed_citedin&from_uid=",33481113)

page =
    polite::bow(cite_link, force = T) %>%
      polite::scrape(query = list(t = "semi-soft", per_page = 1))

/html/body/main/div[9]/div[2]/div[2]/div[1]/div[1]/h3/span
//*[@id="search-results"]/div[2]/div[1]/div[1]/h3/span
//*[@id="search-results"]/div[2]/div[1]/div[1]
//*[@id="search-results"]/div[2]/div[1]/div[1]/h3/span
//*[@id="search-results"]/div[2]/div[1]/div[1]/h3/span
 rvest::html_node(page, xpath = '//*[@id="search-results"]/div[2]/div[1]/div[1]/h3/span') %>% 
   rvest::html_text()

```

```{r}
require(bibliometrix)
bibliometrix::retrievalByAuthorID(23670104100)
```

```{r}
query = query_func("Emma Benn", "", affiliation1 = "Mount Sinai", affiliation2 = "Columbia University", affiliation3 = "")
ids =  entrez_search("pubmed", paste0(query," ","AND"," ","('2008/01/01'[Date - Publication]:'2024/01/01'[Date - Publication])"), retmax = 10000)$ids
recs = entrez_fetch("pubmed", ids, rettype = "xml")
parsed <- XML::xmlTreeParse(recs, useInternalNodes = TRUE)

tibble(
  PUBid = ids
) %>% 
mutate(citations = map(PUBid,pub_citefunc)) %>% 
  unnest(citations) %>% 
  arrange(-citations)
```

```{r}


tibble(name1 = c("Steven","Emma"), 
       name2 = c("Lawrence", "Benn"), 
       affiliation1 = c("Mount Sinai","Mount Sinai"), 
       affiliation2 = c("",""), 
       affiliation3 = c("","")
       ) %>% 
  query_list() %>% 
  
  mutate(qdata  = map(query,query_data))

s=tibble(name1 = c("Steven Lawrence","Emma Benn"), 
       name2 = c("", ""), 
       affiliation1 = c("Mount Sinai","Mount Sinai"), 
       affiliation2 = c("New York University","Columbia University"), 
       affiliation3 = c("","")
       ) %>% 
  batch_metrics() 

p1 =s$parsed[1] %>% 
  paste() %>% 
  xml2::read_xml()
  xml2::as_xml_document()

XML::xmlToDataFrame(nodes = XML::getNodeSet(p1, '//PubmedArticle/MedlineCitation//ArticleTitle'))
  article_data(p1)

s %>% 
  unnest(results) %>% 
  group_by(name1) %>% 
  arrange( name1,-citations,)
  
```

